#!/usr/bin/env php
<?php

use Ske\Util\Application;

require_once __DIR__ . DIRECTORY_SEPARATOR . 'bootstrap.php';

$app = new Application(__DIR__ . '/app/src/main/cli', env());

$result = $app->run($_SERVER);

$app->send($result);
