#!/usr/bin/env php
<?php

use Ske\Util\CommandPrompt;

require_once __DIR__ . DIRECTORY_SEPARATOR . 'bootstrap.php';

$console = new CommandPrompt(__DIR__ . '/app/src/main/cli');

$console->run(--$argc, array_slice($argv, 1));